name: Build xPilot

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  qt_version: 5.15.2

jobs:
  buildLinux:
    runs-on: ubuntu-20.04

    env:
      VATSIM_CLIENT_ID: ${{ secrets.VATSIM_CLINET_ID }}
      VATSIM_CLIENT_KEY: ${{ secrets.VATSIM_CLIENT_KEY }}

    outputs:
      warnings: ${{ steps.warnings.outputs.warnings }}

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.qt_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0