name: Build xPilot

on: [push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  qt_version: 5.15.2
  BUILD_TYPE: Release
  VATSIM_CLIENT_ID: ${{ secrets.VATSIM_CLIENT_ID }}
  VATSIM_CLIENT_KEY: ${{ secrets.VATSIM_CLIENT_KEY }}
  CONFIG_ENCRYPTION_KEY: ${{ secrets.CONFIG_ENCRYPTION_KEY }}

jobs:

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Developer certificate
        env:
          CERTIFICATE: ${{ secrets.APPLE_SIGNING_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.APPLE_SIGNING_CERTIFICATE_PASSWORD }}
        run: ./scripts/make_keychain.sh

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
            version: ${{ env.qt_version }}
          
      - name: Install conan
        run: |
          python3 -m pip install --upgrade pip
          pip3 install conan
          pip3 install conan_package_tools

      - name: Initialize CMake
        run: |
          cmake -E make_directory ${{ github.workspace }}/build

      - name: Install conan packages
        working-directory: ${{ github.workspace }}/build
        run: |
          conan install $GITHUB_WORKSPACE

      - name: CMake
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DVATSIM_CLIENT_ID=$VATSIM_CLIENT_ID -DVATSIM_CLIENT_KEY=$VATSIM_CLIENT_KEY -DCONFIG_ENCRYPTION_KEY=$CONFIG_ENCRYPTION_KEY

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake --build . --config $BUILD_TYPE

      - name: Qt Deploy
        working-directory: ${{ github.workspace }}/build/bin
        run: |
          ${{ env.Qt5_DIR }}/bin/macdeployqt xPilot.app \
          -qmldir=${{ github.workspace}}/Resources \
          -executable=xPilot.app/Contents/MacOS/xPilot

      - name: Code signing
        working-directory: ${{ github.workspace }}/build/bin
        run: |
          codesign --sign "${{ secrets.APPLE_SIGNING_CERTIFICATE_IDENTITY }}" --verify --timestamp ./xPilot.app

      - uses: actions/upload-artifact@master
        with:
          name: xPilot_MacOS
          path: build/bin/xPilot.app
