name: "Build xPilot (Release)"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:

  windows:
    uses: ./.github/workflows/windows.yml
    secrets: inherit

  macos:
    uses: ./.github/workflows/macos.yml
    secrets: inherit

  linux:
    uses: ./.github/workflows/linux.yml
    secrets: inherit

  ########################## Create Release ##########################

  release:
    runs-on: ubuntu-latest
    needs: [linux, windows, macos]
    if: github.ref_type == 'tag' && contains(github.ref_name, 'v')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Reorganize
        run: mv xPilot*/* . && rmdir xPilot*/

      - name: Merge artifacts
        run: |
          mkdir -p artifacts/Linux && mv Linux.zip/* artifacts/Linux
          mkdir -p artifacts/Windows && mv Windows.zip/* artifacts/Windows
          mkdir -p artifacts/MacOS && mv MacOS.zip/* artifacts/MacOS
          cd artifacts && zip -r ../Artifacts-${{ steps.get_version.outputs.version-without-v }}.zip .

      - name: Create release notes
        run: |
          cat > CHANGELOG.txt << EOF
          ## Download
          - [Windows](https://github.com/xpilot-project/xpilot/releases/download/${{ steps.get_version.outputs.version }}/xPilot-${{ steps.get_version.outputs.version-without-v }}-Windows.exe)
          - [macOS](https://github.com/xpilot-project/xpilot/releases/download/${{ steps.get_version.outputs.version }}/xPilot-${{ steps.get_version.outputs.version-without-v }}-MacOS.dmg)
          - [Linux](https://github.com/xpilot-project/xpilot/releases/download/${{ steps.get_version.outputs.version }}/xPilot-${{ steps.get_version.outputs.version-without-v }}-Linux.run)

          ---

          If you enjoy using xPilot, please considering donating to support the future development of the project. Thank you for your support.

          <a href="https://www.paypal.com/donate/?business=7MD45Q2CGTVDS&no_recurring=0&item_name=Thank+you+for+supporting+the+development+of+xPilot.&currency_code=USD"><img src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif"></a>

          ---

          ### Added

          ### Changed

          ### Fixed
          EOF

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          name: xPilot ${{ steps.get_version.outputs.version }}
          prerelease: true
          draft: true
          body_path: CHANGELOG.txt
          files: |
            xPilot*
            Artifacts*.zip
